# Project Information
site_name: OI Wiki
site_description: OI Wiki aims to be a free and lively updated site that integrates resources, in which readers can get interesting and useful knowledge about competitive programming. There are basic knowledge, frequently seen problems, way of solving problems, and useful tools to help everyone to learn quicker and deeper.
site_author: OI Wiki Team
site_url: https://oi-wiki.org
strict: false

# Repository
repo_name: 'OI-wiki/OI-wiki (English)'
repo_url: 'https://github.com/OI-wiki/i18n'
edit_uri: 'https://oiwiki-en.netlify.app/edit-landing/?ref='

# Copyright
copyright: 'Copyright &copy; 2016 - 2021 OI Wiki Team'
#google_analytics:
#  - 'UA-124485594-1'
#  - 'auto'

# Contents
nav:
  - Intro:
    - Getting Started: index.md
    - Non-Trad Problems: intro/non-trad.md #主站删了
    - Deploy in Docker: intro/docker-deploy.md
    - About the project: intro/about.md
    - How to contribute: intro/htc.md
    - Formatting Manual (Chinese): intro/format.md #新增
    - F.A.Q.: intro/faq.md
    - Thanks: intro/thanks.md
  # 同步主站更改
  - Competition:
    - OI Contest Format: contest/index.md
    - 赛事:
      - OI Contest Format: contest/oi.md 
      - ICPC/CCPC Contest Format: contest/icpc.md
    - 题型:
      - 题型概述: contest/problems.md
      - 交互题: contest/interaction.md
    - Studying Roadmap: contest/roadmap.md
    - External Resources: contest/resources.md #修改了翻译
    - 技巧:
      - 读入、输出优化: contest/io.md
      - 常见错误: contest/common-mistakes.md
      - 常见技巧: contest/common-tricks.md
    - 出题相关:
      - 出题: contest/problemsetting.md
  - Tools:
    - Introduction: tools/index.md
    - Code Editor:
      - Vim: tools/editor/vim.md
      - Emacs: tools/editor/emacs.md
      - VS Code: tools/editor/vscode.md
      - Atom: tools/editor/atom.md
      - Eclipse: tools/editor/eclipse.md
      - Notepad++: tools/editor/npp.md
      - Kate: tools/editor/kate.md
      - Dev-C++: tools/editor/devcpp.md
      - Geany: tools/editor/geany.md
      - Xcode: tools/editor/xcode.md
      - GUIDE: tools/editor/guide.md
      - Sublime Text 3: tools/editor/sublime3.md
    - Judgers: tools/judgers.md
    - Terminal: tools/cmd.md
    - WSL (Windows 10): tools/wsl.md
    - Special Judge: tools/special-judge.md
    - Testlib:
      - Testlib 简介: tools/testlib/index.md
      - 通用: tools/testlib/general.md
      - Generator: tools/testlib/generator.md
      - Validator: tools/testlib/validator.md
      - Interactor: tools/testlib/interactor.md
      - Checker: tools/testlib/checker.md
    - Polygon: tools/polygon.md
    - OJ 工具: tools/oj-tool.md
    - LaTeX 入门: tools/latex.md
    - Git: tools/git.md
  - Programming:
    - Introduction: lang/index.md
    - C++ Basics:
      - Hello, World!: lang/helloworld.md
      - C++ Grammar Basics: lang/basic.md
      - Variables: lang/var.md
      - Expressions: lang/op.md
      - Control Flow:
        - Branches: lang/branch.md
        - Loops: lang/loop.md
      - Advanced Data Types:
        - Array: lang/array.md
        - Struct: lang/struct.md
        - Pointer: lang/pointer.md
      - Functions: lang/func.md
      - File Operations: lang/file-op.md
    - C++ Standard Libraries:
      - Introduction: lang/csl/index.md
      - STL Containers:
        - Introduction: lang/csl/container.md
        - Iterator: lang/csl/iterator.md
        - Sequence Container: lang/csl/sequence-container.md
        - Associative Container: lang/csl/associative-container.md
        - Unordered Container: lang/csl/unordered-container.md
        - Container Adapter: lang/csl/container-adapter.md
      - Algorithms in STL: lang/csl/algorithm.md
      - bitset: lang/csl/bitset.md
      - string: lang/csl/string.md
      - pair: lang/csl/pair.md
    - Advanced C++:
      - Classes: lang/class.md
      - Namespaces: lang/namespace.md
      - Value Category: lang/value-category.md
      - Operator Overload: lang/op-overload.md
      - References: lang/reference.md
      - Constants: lang/const.md
      - New features in C++: lang/new.md
      - pb_ds:
        - Introduction: lang/pb-ds/index.md
        - Heap: lang/pb-ds/pq.md
        - Balanced Tree: lang/pb-ds/tree.md
    - C VS C++: lang/c-cpp.md
    - Quick Guide to C++ for Pascal Users: lang/pas-cpp.md
    - Python Quick Guide: lang/python.md
    - Java Quick Guide: lang/java.md
  - Algorithm:
    - Introduction to Algorithm: basic/index.md
    - Enumerate: basic/enumerate.md
    - Simulate: basic/simulate.md #似乎又叫Implementation Problem
    - 递归 & 分治: basic/divide-and-conquer.md #Recursion? 
    - Greddy: basic/greedy.md
    - Sorting:
      - Introduction of Sorting: basic/sort-intro.md
      - Complexity: misc/complexity.md
      - Selection Sort: basic/selection-sort.md
      - Bubble Sort: basic/bubble-sort.md
      - Insertion Sort: basic/insertion-sort.md
      - Counting Sort: basic/counting-sort.md
      - Radix Sort: basic/radix-sort.md
      - Quicksort: basic/quick-sort.md
      - Merge Sort: basic/merge-sort.md
      - Heapsort: basic/heap-sort.md
      - Bucket Sort: basic/bucket-sort.md
      - ShellSort: basic/shell-sort.md
      - Sorting Methods in STL Libraries: basic/stl-sort.md
      - Usage of Sorting: basic/use-of-sort.md
    - 前缀和 & 差分: basic/prefix-sum.md
    - Bisect: basic/binary.md
    - 倍增: basic/binary-lifting.md
    - Constructive Algorithms: basic/construction.md
    # - 交互题: basic/interaction.md #Moved to /Contest
  - Search:
    - Introduction of Searching: search/index.md
    - Depth-First Search (DFS): search/dfs.md
    - Breadth-First Search (BFS): search/bfs.md
    - 双向搜索: search/bidirectional.md
    - 启发式搜索: search/heuristic.md
    - A*: search/astar.md
    - 迭代加深搜索: search/iterative.md
    - IDA*: search/idastar.md
    - 回溯法: search/backtracking.md
    - Dancing Links: search/dlx.md
    - Optimizations: search/opt.md
  - DP:
    - Introduction: dp/index.md
    - Dynamic Programming Fundamentals: dp/basic.md
    - 记忆化搜索: dp/memo.md
    - 背包 DP: dp/knapsack.md
    - 区间 DP: dp/interval.md
    - DAG 上的 DP: dp/dag.md
    - 树形 DP: dp/tree.md
    - 状压 DP: dp/state.md
    - 数位 DP: dp/number.md
    - 插头 DP: dp/plug.md
    - 计数 DP: dp/count.md
    - 动态 DP: dp/dynamic.md
    - 概率 DP: dp/probability.md # 新增
    - DP 优化:
      - 单调队列/单调栈优化: dp/opt/monotonous-queue-stack.md
      - 斜率优化: dp/opt/slope.md
      - 四边形不等式优化: dp/opt/quadrangle.md
      - 状态设计优化: dp/opt/state.md
    - 其它 DP 方法: dp/misc.md
  - String:
    - 字符串部分简介: string/index.md
    - 字符串基础: string/basic.md
    - 标准库: string/lib-func.md
    - 字符串匹配: string/match.md
    - 字符串哈希: string/hash.md
    - 字典树 (Trie): string/trie.md
    - 前缀函数与 KMP 算法: string/kmp.md
    - Boyer-Moore算法: string/bm.md
    - Z 函数（扩展 KMP）: string/z-func.md
    - 自动机: string/automaton.md
    - AC 自动机: string/ac-automaton.md
    # 同步上游
    - 后缀数组 (SA): 
      - 后缀数组简介: string/sa.md
      - 最优原地后缀排序算法: string/sa-optimal-inplace.md # 主站新增
    # Endof 同步上游
    - 后缀自动机 (SAM): string/sam.md
    - 后缀平衡树: string/suffix-bst.md # 主站新增
    - 广义后缀自动机: string/general-sam.md
    - 后缀树: string/suffix-tree.md
    - Manacher: string/manacher.md
    - 回文树: string/pam.md
    - 序列自动机: string/seq-automaton.md
    - 最小表示法: string/minimal-string.md
    - Lyndon 分解: string/lyndon.md
  - Math:
    - 数学部分简介: math/index.md
    - 符号: math/notation.md
    - 复数: math/complex.md
    - 位运算: math/bit.md
    - 快速幂: math/quick-pow.md
    - 进位制: math/base.md
    - 高精度计算: math/bignum.md
    - 平衡三进制: math/balanced-ternary.md # 主站新增
    - 数论:
      - 素数: math/prime.md
      - Meissel-Lehmer 算法: math/meissel-lehmer.md # 新增
      - 最大公约数: math/gcd.md
      - 欧拉函数: math/euler.md
      - 筛法: math/sieve.md
      - 欧拉定理 & 费马小定理: math/fermat.md
      - 类欧几里德算法: math/euclidean.md
      - 裴蜀定理: math/bezouts.md
      - 乘法逆元: math/inverse.md
      - 线性同余方程: math/linear-equation.md
      - 中国剩余定理: math/crt.md
      - 二次剩余: math/quad-residue.md
      - BSGS: math/bsgs.md
      - 原根: math/primitive-root.md
      - 卢卡斯定理: math/lucas.md
      - 莫比乌斯反演: math/mobius.md
      - 杜教筛: math/du.md
      - Powerful Number 筛: math/powerful-number.md # 新增
      - Min_25 筛: math/min-25.md
      - 洲阁筛: math/zhou.md # 新增
      - 分解质因数: math/pollard-rho.md # 新增
      - 连分数: math/continued-fraction.md # 新增
      - Stern-Brocot 树与 Farey 序列: math/stern-brocot.md # Moved from misc
      - Pell 方程: math/pell-equation.md # 新增
    - 多项式:
      - 多项式部分简介: math/poly/intro.md
      - 拉格朗日插值: math/poly/lagrange.md
      - 快速傅里叶变换: math/poly/fft.md
      - 快速数论变换: math/poly/ntt.md
      - 快速沃尔什变换: math/poly/fwt.md
      - 多项式求逆: math/poly/inv.md
      - 多项式开方: math/poly/sqrt.md
      - 多项式除法|取模: math/poly/div-mod.md
      - 多项式对数函数|指数函数: math/poly/ln-exp.md
      - 多项式牛顿迭代: math/poly/newton.md
      - 多项式多点求值|快速插值: math/poly/multipoint-eval-interpolation.md
      - 多项式三角函数: math/poly/tri-func.md
      - 多项式反三角函数: math/poly/inv-tri-func.md
      - 常系数齐次线性递推: math/linear-recurrence.md
    - 生成函数:
      - 生成函数简介: math/gen-func/intro.md
      - 普通生成函数: math/gen-func/ogf.md
      - 指数生成函数: math/gen-func/egf.md
    - 线性代数:
      - 向量: math/vector.md
      - 矩阵: math/matrix.md
      - 高斯消元: math/gauss.md
      - 线性基: math/basis.md
    - 线性规划:
      - 线性规划简介: math/linear-programming.md
      - 单纯形算法: math/simplex.md
    - 组合数学:
      - 排列组合: math/combination.md
      - 卡特兰数: math/catalan.md
      - 斯特林数: math/stirling.md
      - 贝尔数: math/bell.md # 主站新增
      - 伯努利数: math/bernoulli.md # 主站新增
      - 康托展开: math/cantor.md
      - 容斥原理: math/inclusion-exclusion-principle.md
      - 抽屉原理: math/drawer-principle.md
      - Eulerian Number: math/eulerian.md # 主站新增
    - 概率初步: math/expectation.md
    - 置换群: math/permutation-group.md
    - 斐波那契数列: math/fibonacci.md
    - 博弈论: math/game-theory.md
    - 牛顿迭代法: math/newton.md
    - 数值积分: math/integral.md
    - 分段打表: math/dictionary.md
  - Data Structure:
    - Introduction: ds/index.md
    - Stack: ds/stack.md
    - Queue: ds/queue.md
    - Linked List: ds/linked-list.md
    - Hash Table: ds/hash.md
    - 并查集: ds/dsu.md
    - 并查集时间复杂度证明: ds/dsu-complexity.md # 主站无
    - 堆:
      - 堆简介: ds/heap.md
      - 二叉堆: ds/binary-heap.md
      - 配对堆: ds/pairing-heap.md
      - 左偏树: ds/leftist-tree.md
    - 块状数据结构:
      - 分块思想: ds/decompose.md
      - 块状数组: ds/block-array.md
      - 块状链表: ds/block-list.md
      - 树分块: ds/tree-decompose.md
      - Sqrt Tree: ds/sqrt-tree.md
    - 单调栈: ds/monotonous-stack.md
    - 单调队列: ds/monotonous-queue.md
    - ST 表: ds/sparse-table.md
    - 线段树: ds/seg.md
    - 树状数组: ds/fenwick.md
    - 李超线段树: ds/li-chao-tree.md #主站新增
    - 区间最值操作 & 区间历史最值: ds/seg-beats.md
    - 划分树: ds/dividing.md
    - 二叉搜索树 & 平衡树:
      - 二叉搜索树简介: ds/bst.md
      - Treap: ds/treap.md
      - Splay: ds/splay.md
      - WBLT: ds/wblt.md
      - Size Balanced Tree: ds/sbt.md
      - AVL 树: ds/avl.md
      - 替罪羊树: ds/sgt.md
      - 笛卡尔树: ds/cartesian-tree.md
      - 左偏红黑树: ds/llrbt.md
    - 跳表: ds/skiplist.md #主站新增
    - 可持久化数据结构:
      - 可持久化数据结构简介: ds/persistent.md
      - 可持久化线段树: ds/persistent-seg.md
      - 可持久化块状数组: ds/persistent-block-array.md
      - 可持久化平衡树: ds/persistent-balanced.md
      - 可持久化字典树: ds/persistent-trie.md
      - 可持久化可并堆: ds/persistent-heap.md
    - 树套树:
      - 线段树套线段树: ds/seg-in-seg.md
      - 平衡树套线段树: ds/seg-in-balanced.md
      - 线段树套平衡树: ds/balanced-in-seg.md
      - 树状数组套主席树: ds/persistent-in-bit.md
      - 分块套树状数组: ds/bit-in-block-array.md
    - K-D Tree: ds/kdt.md
    - 珂朵莉树: ds/odt.md
    - 动态树:
      - Link Cut Tree: ds/lct.md
      - Euler Tour Tree: ds/ett.md
      - Top Tree: ds/top-tree.md
    - 析合树: ds/divide-combine.md
  - Graph Theory:
    - 图论部分简介: graph/index.md
    - 图论相关概念: graph/concept.md
    - 图的存储: graph/save.md
    - DFS（图论）: graph/dfs.md
    - BFS（图论）: graph/bfs.md
    - 树上问题:
      - 树基础: graph/tree-basic.md
      - 树的直径: graph/tree-diameter.md
      - 最近公共祖先: graph/lca.md
      - 树的重心: graph/tree-centroid.md
      - 树链剖分: graph/hld.md
      - 树上启发式合并: graph/dsu-on-tree.md
      - 虚树: graph/virtual-tree.md
      - 树分治: graph/tree-divide.md
      - 动态树分治: graph/dynamic-tree-divide.md
      - AHU算法: graph/tree-ahu.md
      - 树哈希: graph/tree-hash.md
    - 矩阵树定理: graph/matrix-tree.md
    - 有向无环图: graph/dag.md
    - 拓扑排序: graph/topo.md
    - 最小生成树: graph/mst.md
    - 斯坦纳树: graph/steiner-tree.md # 主站新增
    - 最小树形图: graph/dmst.md # 主站新增
    - 最小直径生成树: graph/mdst.md # 主站新增
    - 最短路: graph/shortest-path.md
    - 拆点: graph/node.md
    - 差分约束: graph/diff-constraints.md
    - k 短路: graph/kth-path.md
    - 同余最短路: graph/mod-shortest-path.md # 主站新增
    - 连通性相关:
      - 强连通分量: graph/scc.md
      - 双连通分量: graph/bcc.md
      - 割点和桥: graph/cut.md
      - 圆方树: graph/block-forest.md # 主站新增
    - 2-SAT: graph/2-sat.md
    - 欧拉图: graph/euler.md
    - 哈密顿图: graph/hamilton.md
    - 二分图: graph/bi-graph.md
    - 最小环: graph/min-circle.md
    - 平面图: graph/planar.md
    - 图的着色: graph/color.md
    - 网络流:
      - 网络流简介: graph/flow.md
      - 最大流: graph/flow/max-flow.md
      - 最小割: graph/flow/min-cut.md
      - 费用流: graph/flow/min-cost.md
      - 上下界网络流: graph/flow/bound.md
    - Stoer-Wagner 算法: graph/stoer-wagner.md # 主站新增
    - 图的匹配: # 主站新增
      - 图匹配: graph/graph-matching/graph-match.md
      - 增广路: graph/graph-matching/augment.md
      - 二分图最大匹配: graph/graph-matching/bigraph-match.md
      - 二分图最大权匹配: graph/graph-matching/bigraph-weight-match.md
      - 一般图最大匹配: graph/graph-matching/general-match.md
      - 一般图最大权匹配: graph/graph-matching/general-weight-match.md
    - Prufer 序列: graph/prufer.md
    - LGV 引理: graph/lgv.md
    - 弦图: graph/chord.md
  - Comp. Geometry:
    - 计算几何部分简介: geometry/index.md
    - 二维计算几何基础: geometry/2d.md
    - 三维计算几何基础: geometry/3d.md
    - 极坐标系: geometry/polar-coordinate.md
    - 距离: geometry/distance.md
    - Pick 定理: geometry/pick.md
    - 三角剖分: geometry/triangulation.md
    - 凸包: geometry/convex-hull.md
    - 扫描线: geometry/scanning.md
    - 旋转卡壳: geometry/rotating-calipers.md
    - 半平面交: geometry/half-plane.md
    - 平面最近点对: geometry/nearest-points.md
    - 随机增量法: geometry/random-incremental.md
    - 反演变换: geometry/inverse.md
    - 计算几何杂项: geometry/misc.md
  - Misc:
    - 杂项简介: misc/index.md
    - 离散化: misc/discrete.md
    - 离线算法:
      - 离线算法简介: misc/offline.md
      - CDQ 分治: misc/cdq-divide.md
      - 整体二分: misc/parallel-binsearch.md
      - 莫队算法:
        - 莫队算法简介: misc/mo-algo-intro.md
        - 普通莫队算法: misc/mo-algo.md
        - 带修改莫队: misc/modifiable-mo-algo.md
        - 树上莫队: misc/mo-algo-on-tree.md
        - 回滚莫队: misc/rollback-mo-algo.md
        - 莫队配合bitset: misc/mo-algo-with-bitset.md
    - 分数规划: misc/frac-programming.md
    - 随机化:
      - 随机函数: misc/random.md
      - 随机化技巧: misc/rand-technique.md # 新增
      - 爬山算法: misc/hill-climbing.md
      - 模拟退火: misc/simulated-annealing.md
    - 悬线法: misc/hoverline.md
    - 计算理论基础: misc/cc-basic.md
    - 字节顺序: misc/endianness.md
    - 约瑟夫问题: misc/josephus.md
    #- Stern-Brocot 树与 Farey 序列: misc/stern-brocot.md # 移动到数论
    - 格雷码: misc/gray-code.md
    - 表达式求值: misc/expression.md
    - 在一台机器上规划任务: misc/job-order.md
    - 主元素问题: misc/main-element.md
  - Topics:
    - RMQ: topic/rmq.md
    - 图的匹配:
      - 图匹配: topic/graph-matching/graph-match.md
      - 增广路: topic/graph-matching/augment.md
      - 二分图最大匹配: topic/graph-matching/bigraph-match.md
      - 一般图匹配: topic/graph-matching/general-match.md
      - 二分图最大权匹配: topic/graph-matching/bigraph-weight-match.md
      - 一般图最大权匹配: topic/graph-matching/general-weight-match.md
  - About Hulu:
    -  About Hulu: intro/hulu.md

# Theme
theme:
  name: null
  custom_dir: 'mkdocs-material/material'
  static_templates:
    - 404.html
  language: 'en'
  palette:
    primary: 'white'
    accent: 'red'
  include_search_page: false
  search_index_only: true
  favicon: 'https://cdn.jsdelivr.net/npm/oicdn@0.0.1/favicon.ico'

  logo:
    icon: 'school'
  feature:
    tabs: true
  font:
    text: 'Fira Sans'
    code: 'Fira Mono'

# Customization
extra:
  search:
    language: 'jp'
  disqus: 'OI-Wiki'
  copyright: '<a href="https://creativecommons.org/licenses/by-sa/4.0/deed">CC BY-SA 4.0</a> & <a href="https://github.com/zTrix/sata-license">SATA</a>'
  pagetime: 'on'
  manifest: 'manifest.webmanifest'
  githash: '37d0f772'
  # notice:
  #   title: 'Hi'
  #   message: '欢迎点击这里对 OI Wiki 提一点建议'
  #   url: 'https://wj.qq.com/s2/4467592/b1e9'
  #   position: 'topCenter'
  #   progressBar: false
  #   timeout: false

extra_javascript:
  - '_static/js/extra.js?v=16'
  


extra_css:
  - '_static/css/extra.css?v=13'

# Extensions
markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
      linenums: true
  - def_list
  - footnotes
  - meta
  - toc:
      permalink: true
  - pymdownx.arithmatex
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.progressbar
  - pymdownx.smartsymbols
  - pymdownx.superfences:
      custom_fences:
        - name: math
          class: arithmatex
          format: !!python/name:pymdownx.arithmatex.fence_mathjax_format
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
