# Project Information
site_name: OI Wiki
site_description: OI Wiki aims to be a free and lively updated site that integrates resources, in which readers can get interesting and useful knowledge about competitive programming. There are basic knowledge, frequently seen problems, way of solving problems, and useful tools to help everyone to learn quicker and deeper.
site_author: OI Wiki Team
site_url: https://oi-wiki.org
strict: false

# Repository
repo_name: 'OI-wiki/OI-wiki (English)'
repo_url: 'https://github.com/OI-wiki/i18n'
edit_uri: 'https://oiwiki-en.netlify.app/edit-landing/?ref='

# Copyright
copyright: 'Copyright &copy; 2016 - 2021 OI Wiki Team'
#google_analytics:
#  - 'UA-124485594-1'
#  - 'auto'

# Contents
nav:
  - Intro:
    - Getting Started: index.md
    - Non-Trad Problems: intro/non-trad.md #主站删了
    - Deploy in Docker: intro/docker-deploy.md
    - About the project: intro/about.md
    - How to contribute: intro/htc.md
    - Formatting Manual (Chinese): intro/format.md #新增
    - F.A.Q.: intro/faq.md
    - Thanks: intro/thanks.md
  - Competitions:
    - Introduction: contest/index.md
    - Competitions:
      - OI Contest Format: contest/oi.md 
      - ICPC/CCPC Contest Format: contest/icpc.md
    - Problem Types:
      - Introduction: contest/problems.md
      - Interaction Problem: contest/interaction.md
    - Studying Roadmap: contest/roadmap.md
    - External Resources: contest/resources.md #修改了翻译
    - Tricks:
      - IO Optimization: contest/io.md
      - Common Mistakes: contest/common-mistakes.md
      - Common Tricks: contest/common-tricks.md
    - Problemsetting: contest/problemsetting.md
  - Tools:
    - Introduction: tools/index.md
    - Editors and IDEs:
      - Vim: tools/editor/vim.md
      - Emacs: tools/editor/emacs.md
      - VS Code: tools/editor/vscode.md
      - Atom: tools/editor/atom.md
      - Eclipse: tools/editor/eclipse.md
      - Notepad++: tools/editor/npp.md
      - Kate: tools/editor/kate.md
      - Dev-C++: tools/editor/devcpp.md
      - Geany: tools/editor/geany.md
      - Xcode: tools/editor/xcode.md
      - GUIDE: tools/editor/guide.md
      - Sublime Text 3: tools/editor/sublime3.md
    - Judging Tools: tools/judgers.md
    - Commandline: tools/cmd.md
    - WSL (Windows 10): tools/wsl.md
    - Special Judge: tools/special-judge.md
    - Testlib:
      - Introduction: tools/testlib/index.md
      - General: tools/testlib/general.md
      - Generator: tools/testlib/generator.md
      - Validator: tools/testlib/validator.md
      - Interactor: tools/testlib/interactor.md
      - Checker: tools/testlib/checker.md
    - Polygon: tools/polygon.md
    - OJ Tools: tools/oj-tool.md
    - Beginner LaTeX: tools/latex.md
  - Programming:
    - Introduction: lang/index.md
    - Editing tools:
      - Vim: lang/editor/vim.md
      - Emacs: lang/editor/emacs.md
      - VS Code: lang/editor/vscode.md
      - Atom: lang/editor/atom.md
      - Eclipse: lang/editor/eclipse.md
      - Notepad++: lang/editor/npp.md
      - Dev-C++: lang/editor/devcpp.md
      - Geany: lang/editor/geany.md
    - C++ Basics:
      - Hello, World!: lang/helloworld.md
      - C++ Grammar Basics: lang/basic.md
      - Variables: lang/var.md
      - Expressions: lang/op.md
      - Control Flow:
        - Branches: lang/branch.md
        - Loops: lang/loop.md
      - Advanced Data Types:
        - Array: lang/array.md
        - Struct: lang/struct.md
        - Pointer: lang/pointer.md
      - Functions: lang/func.md
      - File Operations: lang/file-op.md
    - C++ Standard Libraries:
      - Introduction: lang/csl/index.md
      - STL Containers:
        - Introduction: lang/csl/container.md
        - Iterator: lang/csl/iterator.md
        - Sequence Container: lang/csl/sequence-container.md
        - Associative Container: lang/csl/associative-container.md
        - Unordered Container: lang/csl/unordered-container.md
        - Container Adapter: lang/csl/container-adapter.md
      - Algorithms in STL: lang/csl/algorithm.md
      - bitset: lang/csl/bitset.md
      - string: lang/csl/string.md
    - Advanced C++:
      - Classes: lang/class.md
      - Namespaces: lang/namespace.md
      - References: lang/reference.md
      - Constants: lang/const.md
      - New features in C++: lang/new.md
      - pb_ds:
        - Introduction: lang/pb-ds/index.md
        - Heap: lang/pb-ds/pq.md
        - Balanced Tree: lang/pb-ds/tree.md
    - C VS C++: lang/c-cpp.md
    - Quick Guide to C++ for Pascal Users: lang/pas-cpp.md
    - Python Quick Guide: lang/python.md
    - Java Quick Guide: lang/java.md
  - Algorithm:
    - Introduction to Algorithm: basic/index.md
    - Complexity: basic/complexity.md
    - Enumerate: basic/enumerate.md
    - Simulate: basic/simulate.md #似乎又叫Implementation Problem
    - Recursion, Divide and Conquer: basic/divide-and-conquer.md
    - Greddy: basic/greedy.md
    - Sorting:
      - Introduction of Sorting: basic/sort-intro.md
      - Selection Sort: basic/selection-sort.md
      - Bubble Sort: basic/bubble-sort.md
      - Insertion Sort: basic/insertion-sort.md
      - Counting Sort: basic/counting-sort.md
      - Radix Sort: basic/radix-sort.md
      - Quicksort: basic/quick-sort.md
      - Merge Sort: basic/merge-sort.md
      - Heapsort: basic/heap-sort.md
      - Bucket Sort: basic/bucket-sort.md
      - ShellSort: basic/shell-sort.md
      - Tournament Sort: basic/tournament-sort.md
      - Sorting Methods in STL Libraries: basic/stl-sort.md
      - Usage of Sorting: basic/use-of-sort.md
    - Prefix Sum & Differences: basic/prefix-sum.md
    - Bisect: basic/binary.md
    - Binary Lifting: basic/binary-lifting.md
    - Constructive Algorithms: basic/construction.md
  - Search:
    - Introduction of Searching: search/index.md
    - Depth-First Search (DFS): search/dfs.md
    - Breadth-First Search (BFS): search/bfs.md
    - Bidrectional Search: search/bidirectional.md
    - Heuristic Search: search/heuristic.md
    - A*: search/astar.md
    - Iterative Search: search/iterative.md
    - IDA*: search/idastar.md
    - Backtracing: search/backtracking.md
    - Dancing Links: search/dlx.md
    - Optimizations: search/opt.md
  - DP:
    - Introduction: dp/index.md
    - Dynamic Programming Fundamentals: dp/basic.md
    - Memorized Search: dp/memo.md
    - Knapsack: dp/knapsack.md
    - Interval DP: dp/interval.md
    - DP on DAG: dp/dag.md
    - Tree DP: dp/tree.md
    - State Compression DP: dp/state.md
    - Digit DP: dp/number.md
    - Plug DP: dp/plug.md
    - Counting DP: dp/count.md
    - Dynamic DP: dp/dynamic.md
    - Probability DP: dp/probability.md # 新增
    - Optimizations:
      - Monotonous Queue/Stack: dp/opt/monotonous-queue-stack.md
      - Slope: dp/opt/slope.md
      - Quadrangle: dp/opt/quadrangle.md
      - State Designing: dp/opt/state.md
    - Misc. DP: dp/misc.md
  - String:
    - Introduction: string/index.md
    - Basics: string/basic.md
    - Standard Library: string/lib-func.md
    - String Matching: string/match.md
    - Hashing: string/hash.md
    - Trie: string/trie.md
    - Prefix Function & KMP: string/kmp.md
    - Boyer-Moore: string/bm.md
    - Z Function (Ex. KMP): string/z-func.md
    - Automation: string/automaton.md
    - AC Automation: string/ac-automaton.md
    - Suffix Array: 
      - Introduction: string/sa.md
      - Optimal In-place Suffix Sort: string/sa-optimal-inplace.md
    - Suffix Automation (SAM): string/sam.md
    - Suffix Binary Search Tree: string/suffix-bst.md
    - General SAM: string/general-sam.md
    - Suffix Sum: string/suffix-tree.md
    - Manacher: string/manacher.md
    - Palindrome Tree: string/pam.md
    - Sequence Automation: string/seq-automaton.md
    - Minimal Representation: string/minimal-string.md
    - Lyndon Decomposition: string/lyndon.md
  - Math:
    - Introduction: math/index.md
    - Notations: math/notation.md
    - Complex Number: math/complex.md
    - Bit Operations: math/bit.md
    - Quick Power: math/quick-pow.md
    - Bases: math/base.md
    - BigNum: math/bignum.md
    - Balanced Ternary: math/balanced-ternary.md # 主站新增
    - Number Theory:
      - Prime: math/prime.md
      - Meissel-Lehmer Algorithm: math/meissel-lehmer.md # 新增
      - Greatest Common Divisor: math/gcd.md
      - Euler Function: math/euler.md
      - Sieve of Eratosthenes: math/sieve.md
      - Euler & Fermat's Little Theorem: math/fermat.md
      - Euclidean-like Algorithm: math/euclidean.md
      - Bezout's Theorem: math/bezouts.md
      - Multiplicative Inverse: math/inverse.md
      - Congruence Equation: math/linear-equation.md
      - Chinese Remainder Theorem: math/crt.md
      - Quad Residue: math/quad-residue.md
      - BSGS: math/bsgs.md
      - Primitive Root: math/primitive-root.md
      - Lucas's Theorem: math/lucas.md
      - Mobius Inversion Formula: math/mobius.md
      - Du's Algorithm: math/du.md # dont know how to ranslate
      - Powerful Number (Ex. Du's): math/powerful-number.md # dont know how to ranslate
      - Min_25's Algotithm: math/min-25.md # dont know how to ranslate
      - Zhouge Algorithm: math/zhou.md # dont know how to ranslate
      - Pollard-Rho: math/pollard-rho.md # 新增
      - Continued Fraction: math/continued-fraction.md # 新增
      - Stern-Brocot Tree & Farey Sequence: math/stern-brocot.md # Moved from misc
      - Pell Equation: math/pell-equation.md # 新增
    - 多项式:
      - 多项式部分简介: math/poly/intro.md
      - 拉格朗日插值: math/poly/lagrange.md
      - 快速傅里叶变换: math/poly/fft.md
      - 快速数论变换: math/poly/ntt.md
      - 快速沃尔什变换: math/poly/fwt.md
      - 多项式求逆: math/poly/inv.md
      - 多项式开方: math/poly/sqrt.md
      - 多项式除法|取模: math/poly/div-mod.md
      - 多项式对数函数|指数函数: math/poly/ln-exp.md
      - 多项式牛顿迭代: math/poly/newton.md
      - 多项式多点求值|快速插值: math/poly/multipoint-eval-interpolation.md
      - 多项式三角函数: math/poly/tri-func.md
      - 多项式反三角函数: math/poly/inv-tri-func.md
      - 常系数齐次线性递推: math/linear-recurrence.md
    - 生成函数:
      - 生成函数简介: math/gen-func/intro.md
      - 普通生成函数: math/gen-func/ogf.md
      - 指数生成函数: math/gen-func/egf.md
    - 线性代数:
      - 向量: math/vector.md
      - 矩阵: math/matrix.md
      - 高斯消元: math/gauss.md
      - 线性基: math/basis.md
    - 线性规划:
      - 线性规划简介: math/linear-programming.md
      - 单纯形算法: math/simplex.md
    - 组合数学:
      - 排列组合: math/combination.md
      - 卡特兰数: math/catalan.md
      - 斯特林数: math/stirling.md
      - 贝尔数: math/bell.md # 主站新增
      - 伯努利数: math/bernoulli.md # 主站新增
      - 康托展开: math/cantor.md
      - 容斥原理: math/inclusion-exclusion-principle.md
      - 抽屉原理: math/drawer-principle.md
      - Eulerian Number: math/eulerian.md # 主站新增
    - 概率初步: math/expectation.md
    - 置换群: math/permutation-group.md
    - 斐波那契数列: math/fibonacci.md
    - 博弈论: math/game-theory.md
    - 牛顿迭代法: math/newton.md
    - 数值积分: math/integral.md
    - 分段打表: math/dictionary.md
  - Data Structure:
    - Introduction: ds/index.md
    - Stack: ds/stack.md
    - Queue: ds/queue.md
    - Linked List: ds/linked-list.md
    - Hash Table: ds/hash.md
    - Joint Set:
      - Joint Set: ds/dsu.md
      - Time Complexity: ds/dsu-complexity.md # 主站无
    - Heap:
      - Introduction: ds/heap.md
      - Binary Heap: ds/binary-heap.md
      - Pairing Heap: ds/pairing-heap.md
      - Leftist Tree: ds/leftist-tree.md
    - Block Data Structure:
      - Core Idea: ds/decompose.md
      - Array: ds/block-array.md
      - Linked List: ds/block-list.md
      - Tree: ds/tree-decompose.md
      - Sqrt Tree: ds/sqrt-tree.md
    - Monotonous Stack: ds/monotonous-stack.md
    - Monotonous Queue: ds/monotonous-queue.md
    - Sparse Table: ds/sparse-table.md
    - Segment Tree: ds/seg.md
    - Fenwick: ds/fenwick.md
    - Li Chao Tree: ds/li-chao-tree.md #主站新增
    - Segment History Extreme: ds/seg-beats.md
    - Dividing Tree: ds/dividing.md
    - Binary Search / Balanced Trees:
      - Introduction: ds/bst.md
      - Treap: ds/treap.md
      - Splay: ds/splay.md
      - WBLT: ds/wblt.md
      - Size Balanced Tree: ds/sbt.md
      - AVL: ds/avl.md
      - Scapegoat Tree: ds/sgt.md
      - Cartesian Tree: ds/cartesian-tree.md
      - Left-leaning Red/Black Tree: ds/llrbt.md
    - Skiplist: ds/skiplist.md #主站新增
    - Persistent Data Structure:
      - Introduction: ds/persistent.md
      - Segment Tree: ds/persistent-seg.md
      - Block Array: ds/persistent-block-array.md
      - Balanced Tree: ds/persistent-balanced.md
      - Trie: ds/persistent-trie.md
      - Heap: ds/persistent-heap.md
    - Tree in Tree:
      - Segment in Segment: ds/seg-in-seg.md
      - Segment in Balanced: ds/seg-in-balanced.md
      - Balanced in Segment: ds/balanced-in-seg.md
      - Persistent Segment in Fenwick: ds/persistent-in-bit.md
      - Fenwick in Block Array: ds/bit-in-block-array.md
    - K-D Tree: ds/kdt.md
    - ODT: ds/odt.md
    - Dynamic Tree:
      - Link Cut Tree: ds/lct.md
      - Euler Tour Tree: ds/ett.md
      - Top Tree: ds/top-tree.md
    - Divide Combine Tree: ds/divide-combine.md
  - Graph Theory:
    - Introduction: graph/index.md
    - Concepts: graph/concept.md
    - Storage: graph/save.md
    - DFS（Graph Theory）: graph/dfs.md
    - BFS（Graph Theory）: graph/bfs.md
    - 树上问题:
      - 树基础: graph/tree-basic.md
      - 树的直径: graph/tree-diameter.md
      - 最近公共祖先: graph/lca.md
      - 树的重心: graph/tree-centroid.md
      - 树链剖分: graph/hld.md
      - 树上启发式合并: graph/dsu-on-tree.md
      - 虚树: graph/virtual-tree.md
      - 树分治: graph/tree-divide.md
      - 动态树分治: graph/dynamic-tree-divide.md
      - AHU算法: graph/tree-ahu.md
      - 树哈希: graph/tree-hash.md
    - 矩阵树定理: graph/matrix-tree.md
    - 有向无环图: graph/dag.md
    - 拓扑排序: graph/topo.md
    - 最小生成树: graph/mst.md
    - 斯坦纳树: graph/steiner-tree.md # 主站新增
    - 最小树形图: graph/dmst.md # 主站新增
    - 最小直径生成树: graph/mdst.md # 主站新增
    - 最短路: graph/shortest-path.md
    - 拆点: graph/node.md
    - 差分约束: graph/diff-constraints.md
    - k 短路: graph/kth-path.md
    - 同余最短路: graph/mod-shortest-path.md # 主站新增
    - 连通性相关:
      - 强连通分量: graph/scc.md
      - 双连通分量: graph/bcc.md
      - 割点和桥: graph/cut.md
      - 圆方树: graph/block-forest.md # 主站新增
    - 2-SAT: graph/2-sat.md
    - 欧拉图: graph/euler.md
    - 哈密顿图: graph/hamilton.md
    - 二分图: graph/bi-graph.md
    - 最小环: graph/min-circle.md
    - 平面图: graph/planar.md
    - 图的着色: graph/color.md
    - 网络流:
      - 网络流简介: graph/flow.md
      - 最大流: graph/flow/max-flow.md
      - 最小割: graph/flow/min-cut.md
      - 费用流: graph/flow/min-cost.md
      - 上下界网络流: graph/flow/bound.md
    - Stoer-Wagner 算法: graph/stoer-wagner.md # 主站新增
    - 图的匹配: # 主站新增
      - 图匹配: graph/graph-matching/graph-match.md
      - 增广路: graph/graph-matching/augment.md
      - 二分图最大匹配: graph/graph-matching/bigraph-match.md
      - 二分图最大权匹配: graph/graph-matching/bigraph-weight-match.md
      - 一般图最大匹配: graph/graph-matching/general-match.md
      - 一般图最大权匹配: graph/graph-matching/general-weight-match.md
    - Prufer 序列: graph/prufer.md
    - LGV 引理: graph/lgv.md
    - 弦图: graph/chord.md
  - Comp. Geometry:
    - 计算几何部分简介: geometry/index.md
    - 二维计算几何基础: geometry/2d.md
    - 三维计算几何基础: geometry/3d.md
    - 极坐标系: geometry/polar-coordinate.md
    - 距离: geometry/distance.md
    - Pick 定理: geometry/pick.md
    - 三角剖分: geometry/triangulation.md
    - 凸包: geometry/convex-hull.md
    - 扫描线: geometry/scanning.md
    - 旋转卡壳: geometry/rotating-calipers.md
    - 半平面交: geometry/half-plane.md
    - 平面最近点对: geometry/nearest-points.md
    - 随机增量法: geometry/random-incremental.md
    - 反演变换: geometry/inverse.md
    - 计算几何杂项: geometry/misc.md
  - Misc:
    - Introduction: misc/index.md
    - 离散化: misc/discrete.md
    - 离线算法:
      - 离线算法简介: misc/offline.md
      - CDQ 分治: misc/cdq-divide.md
      - 整体二分: misc/parallel-binsearch.md
      - 莫队算法:
        - 莫队算法简介: misc/mo-algo-intro.md
        - 普通莫队算法: misc/mo-algo.md
        - 带修改莫队: misc/modifiable-mo-algo.md
        - 树上莫队: misc/mo-algo-on-tree.md
        - 回滚莫队: misc/rollback-mo-algo.md
        - 莫队配合bitset: misc/mo-algo-with-bitset.md
    - 分数规划: misc/frac-programming.md
    - 随机化:
      - 随机函数: misc/random.md
      - 随机化技巧: misc/rand-technique.md # 新增
      - 爬山算法: misc/hill-climbing.md
      - 模拟退火: misc/simulated-annealing.md
    - 悬线法: misc/hoverline.md
    - 计算理论基础: misc/cc-basic.md
    - 字节顺序: misc/endianness.md
    - 约瑟夫问题: misc/josephus.md
    #- Stern-Brocot 树与 Farey 序列: misc/stern-brocot.md # 移动到数论
    - 格雷码: misc/gray-code.md
    - 表达式求值: misc/expression.md
    - 在一台机器上规划任务: misc/job-order.md
    - 主元素问题: misc/main-element.md
  - Topics:
    - RMQ: topic/rmq.md
    - 图的匹配:
      - 图匹配: topic/graph-matching/graph-match.md
      - 增广路: topic/graph-matching/augment.md
      - 二分图最大匹配: topic/graph-matching/bigraph-match.md
      - 一般图匹配: topic/graph-matching/general-match.md
      - 二分图最大权匹配: topic/graph-matching/bigraph-weight-match.md
      - 一般图最大权匹配: topic/graph-matching/general-weight-match.md
  - About Hulu:
    -  About Hulu: intro/hulu.md

# Theme
theme:
  name: null
  custom_dir: 'mkdocs-material/material'
  static_templates:
    - 404.html
  language: 'en'
  palette:
    primary: 'white'
    accent: 'red'
  include_search_page: false
  search_index_only: true
  favicon: 'https://cdn.jsdelivr.net/npm/oicdn@0.0.1/favicon.ico'

  logo:
    icon: 'school'
  feature:
    tabs: true
  font:
    text: 'Fira Sans'
    code: 'Fira Mono'

# Customization
extra:
  search:
    language: 'jp'
  disqus: 'OI-Wiki'
  copyright: '<a href="https://creativecommons.org/licenses/by-sa/4.0/deed">CC BY-SA 4.0</a> & <a href="https://github.com/zTrix/sata-license">SATA</a>'
  pagetime: 'on'
  manifest: 'manifest.webmanifest'
  githash: '37d0f772'
  # notice:
  #   title: 'Hi'
  #   message: '欢迎点击这里对 OI Wiki 提一点建议'
  #   url: 'https://wj.qq.com/s2/4467592/b1e9'
  #   position: 'topCenter'
  #   progressBar: false
  #   timeout: false

extra_javascript:
  - '_static/js/extra.js?v=16'
  


extra_css:
  - '_static/css/extra.css?v=13'

# Extensions
markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
      linenums: true
  - def_list
  - footnotes
  - meta
  - toc:
      permalink: true
  - pymdownx.arithmatex
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.progressbar
  - pymdownx.smartsymbols
  - pymdownx.superfences:
      custom_fences:
        - name: math
          class: arithmatex
          format: !!python/name:pymdownx.arithmatex.fence_mathjax_format
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
